@startuml
'https://plantuml.com/class-diagram

title Underground Music Playlist Service

enum Genres {
    ALT_ROCK
    HIPHOP_RNB
    COUNTRY
    OLDIES
    ELECTRONIC
    SOUNDTRACKS
    REGGAE
    INDIE
    INSTRUMENTAL
    POP
    JAZZ
    LATIN
}

class GetExistingUser {
    -Logger log
    -UserDao userDao
    -ProvidedPlaylistDao providedPlaylistDao
    -UserPlaylistDao userPlaylistDao
    +handleRequest (final GetProvidedPlaylistRequest getProvidedPlaylistRequest, Context context) : GetProvidedPlaylistResult
}

@enduml